# Generated by Django 4.2.1 on 2023-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuespending',
            name='typeCat',
            field=models.CharField(choices=[('0', 'Comida'), ('1', 'Serviço'), ('2', 'Eletrônico'), ('3', 'Vestuário'), ('4', 'Entretenimento'), ('5', 'Outros')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
